/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Apply MDAST commands and convert to HAST handle in one step.
 * The MDAST handle is consumed (emptied).
 */
export declare function applyCommandsAndConvertToHastHandle(handle: ArenaHandle, commandBuf: Uint8Array): ArenaHandle

/** Apply a command buffer to a handle's arena in-place. No serialize/deserialize. */
export declare function applyCommandsToHandle(handle: ArenaHandle, commandBuf: Uint8Array): void

/** Apply a command buffer to an MDAST handle in-place. */
export declare function applyCommandsToMdastHandle(handle: ArenaHandle, commandBuf: Uint8Array): void

/** Compile a handle's HAST arena to MDX JavaScript. Does not consume the handle. */
export declare function compileHandle(handle: ArenaHandle, options?: JsMdxOptions | undefined | null): string

/** Compile MDX source directly to JavaScript. */
export declare function compileMdx(source: string, options?: JsMdxOptions | undefined | null): string

/** Convert an MDAST handle to a HAST handle. The MDAST handle is consumed (emptied). */
export declare function convertMdastToHastHandle(handle: ArenaHandle): ArenaHandle

/**
 * Parse markdown source and convert to HAST. Returns an opaque handle.
 * The arena stays in Rust memory — no buffer is copied to JS.
 */
export declare function createHastHandle(source: string): ArenaHandle

/** Parse markdown source into an MDAST arena handle. */
export declare function createMdastHandle(source: string): ArenaHandle

/** Parse MDX source and convert to HAST. Returns an opaque handle. */
export declare function createMdxHastHandle(source: string): ArenaHandle

/** Parse MDX source into an MDAST arena handle. */
export declare function createMdxMdastHandle(source: string): ArenaHandle

/**
 * Release the arena memory held by a handle. The handle becomes empty
 * but remains valid (subsequent calls are no-ops or return empty results).
 */
export declare function dropHandle(handle: ArenaHandle): void

/** Get the source string from an MDAST handle. */
export declare function getHandleSource(handle: ArenaHandle): string

/** Read the node_data JSON blob for a node. Returns null if none is set. */
export declare function getNodeData(handle: ArenaHandle, nodeId: number): string | null

/** MDX compile options passed from JavaScript. */
export interface JsMdxOptions {
  /**
   * Static subtree optimization. If provided, static subtrees are collapsed
   * into raw HTML strings using the specified component and prop.
   */
  optimizeStatic?: JsOptimizeStaticConfig
}

/** Static optimization config passed from JavaScript. */
export interface JsOptimizeStaticConfig {
  /** Component/element name to wrap collapsed HTML in (e.g. "Fragment", "div"). */
  component: string
  /** Prop name for the HTML string (e.g. "set:html", "dangerouslySetInnerHTML"). */
  prop: string
  /** If true, prop value is wrapped as `{ __html: "..." }` (React-style). */
  wrapPropValue?: boolean
  /** Element tag names to exclude from collapsing. */
  ignoreElements?: Array<string>
}

/** A subscription passed from JS. */
export interface JsSubscription {
  nodeType: number
  tagFilter: Array<string>
}

/**
 * Parse a JavaScript expression and return its ESTree-compatible AST as a JSON string.
 * Returns null if parsing fails. The JS layer calls JSON.parse (faster than serde_json → NAPI).
 */
export declare function parseExpression(source: string): string | null

/** Parse Markdown source and return HTML string directly. */
export declare function parseToHtml(source: string): string

/** Render a handle's HAST arena to HTML. Does not consume the handle. */
export declare function renderHandle(handle: ArenaHandle): string

/** Serialize a handle's arena to a binary buffer (for fallback paths like transformRoot). */
export declare function serializeHandle(handle: ArenaHandle): Uint8Array

/** Serialize an MDAST handle to a binary buffer (read-only snapshot for JS visitor). */
export declare function serializeMdastHandle(handle: ArenaHandle): Uint8Array

/** Set the `data` blob (JSON bytes) for a node in the handle's arena. */
export declare function setNodeData(handle: ArenaHandle, nodeId: number, json: Uint8Array): void

/**
 * Collect the concatenated text content of a node and all its descendants.
 * Walks entirely in Rust — no per-child NAPI round-trips.
 */
export declare function textContentHandle(handle: ArenaHandle, nodeId: number): string

/** Walk a handle's arena and return matched nodes as a flat binary buffer. */
export declare function walkHandle(handle: ArenaHandle, subscriptions: Array<JsSubscription>): Uint8Array

/** Walk an MDAST handle's arena and return matched nodes as a flat binary buffer. */
export declare function walkMdastHandle(handle: ArenaHandle, subscriptions: Array<JsSubscription>): Uint8Array
