packages:
  - packages/*
  - packages/vite-plugin-satteri/example
  - examples
  - website

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "esbuild"

supportedArchitectures:
  cpu:
    - current
    - wasm32
