fn main() {
    generate_tests_from_spec()
}

// If the "gen-tests" feature is absent,
// this function will be compiled down to nothing
#[cfg(any(not(feature = "gen-tests"), not(feature = "std")))]
fn generate_tests_from_spec() {}

// If the feature is present, generate tests
// from any .txt file present in the specs/ directory
//
// Test cases are present in the files in the
// following format:
//
// ```````````````````````````````` example
// markdown
// .
// expected html output
// ````````````````````````````````
#[cfg(all(feature = "gen-tests", feature = "std"))]
fn generate_tests_from_spec() {
    use std::fs::{self, File};
    use std::io::{Read, Write};
    use std::path::PathBuf;

    // This is a hardcoded path to the CommonMark spec because it is not situated in
    // the specs/ directory. It's in an array to easily chain it to the other iterator
    // and make it easy to eventually add other hardcoded paths in the future if needed
    let hardcoded = [
        "./third_party/CommonMark/spec.txt",
        "./third_party/CommonMark/smart_punct.txt",
        "./third_party/GitHub/gfm_table.txt",
        "./third_party/GitHub/gfm_strikethrough.txt",
        "./third_party/GitHub/gfm_tasklist.txt",
    ];
    let hardcoded_iter = hardcoded.iter().map(PathBuf::from);

    // Create an iterator over the files in the specs/ directory that have a .txt extension
    let mut spec_files = fs::read_dir("./specs")
        .expect("Could not find the 'specs' directory")
        .filter_map(Result::ok)
        .map(|d| d.path())
        .filter(|p| p.extension().map(|e| e.to_owned()).is_some())
        .chain(hardcoded_iter)
        .collect::<Vec<_>>();
    // Sort by spec names
    spec_files.sort_by(|p, q| p.file_stem().cmp(&q.file_stem()));
    let spec_files = spec_files;

    for file_path in &spec_files {
        let mut raw_spec = String::new();

        File::open(file_path)
            .and_then(|mut f| f.read_to_string(&mut raw_spec))
            .expect("Could not read the spec file");

        let rs_test_file = PathBuf::from("./tests/suite/")
            .join(file_path.file_name().expect("Invalid filename"))
            .with_extension("rs");

        let mut spec_rs = File::create(&rs_test_file)
            .unwrap_or_else(|_| panic!("Could not create {:?}", rs_test_file));

        let spec_name = file_path.file_stem().unwrap().to_str().unwrap();

        let base_options = base_options_for_spec(spec_name);

        let spec = Spec::new(&raw_spec);
        let mut n_tests = 0;

        spec_rs
            .write_all(b"// This file is auto-generated by the build script\n")
            .unwrap();
        spec_rs
            .write_all(b"// Please, do not modify it manually\n")
            .unwrap();
        spec_rs
            .write_all(b"\nuse super::test_markdown_html;\n")
            .unwrap();

        for (i, testcase) in spec.enumerate() {
            spec_rs
                .write_fmt(format_args!(
                    r###"
#[test]
fn {}_test_{i}() {{
    let original = r##"{original}"##;
    let expected = r##"{expected}"##;

    test_markdown_html(original, expected, {base_options}, {smart_punct}, {metadata_blocks}, {subscript}, {wikilinks}, {deflists}, {container_extensions});
}}
"###,
                    spec_name,
                    i = i + 1,
                    original = testcase.original,
                    expected = testcase.expected,
                    base_options = base_options,
                    smart_punct = testcase.smart_punct,
                    metadata_blocks = testcase.metadata_blocks,
                    subscript = testcase.subscript,
                    wikilinks = testcase.wikilinks,
                    deflists = testcase.deflists,
                    container_extensions = testcase.container_extensions,
                ))
                .unwrap();

            n_tests += 1;
        }

        println!(
            "cargo:warning=Generated {} tests in {:?}",
            n_tests, rs_test_file
        );
    }

    // write mods to suite/mod.rs
    let suite_mod_file = PathBuf::from("./tests/suite/mod").with_extension("rs");

    let mut mod_rs = File::create(&suite_mod_file)
        .unwrap_or_else(|_| panic!("Could not create {:?}", suite_mod_file));

    mod_rs
        .write_all(b"// This file is auto-generated by the build script\n")
        .unwrap();
    mod_rs
        .write_all(b"// Please, do not modify it manually\n")
        .unwrap();
    mod_rs
        .write_all(b"\npub use super::test_markdown_html;\n\n")
        .unwrap();

    for file_path in &spec_files {
        let mod_name = file_path.file_stem().unwrap().to_str().unwrap();
        mod_rs.write_all(b"mod ").unwrap();
        mod_rs.write_all(mod_name.as_bytes()).unwrap();
        mod_rs.write_all(b";\n").unwrap();
    }
}

#[cfg(feature = "gen-tests")]
fn base_options_for_spec(spec_name: &str) -> u32 {
    // Option bit values from src/lib.rs
    const TABLES: u32 = 1 << 1;
    const FOOTNOTES: u32 = 1 << 2;
    const STRIKETHROUGH: u32 = 1 << 3;
    const TASKLISTS: u32 = 1 << 4;
    const HEADING_ATTRIBUTES: u32 = 1 << 6;
    const MATH: u32 = 1 << 10;
    const GFM: u32 = 1 << 11;
    const SUPERSCRIPT: u32 = 1 << 13;
    const MATH_MULTI_DOLLAR: u32 = 1 << 23;

    match spec_name {
        // CommonMark spec: no extensions
        "spec" | "smart_punct" => 0,

        // GFM specs: GFM + the specific extension
        "gfm_table" => GFM | TABLES,
        "gfm_strikethrough" => GFM | STRIKETHROUGH,
        "gfm_tasklist" => GFM | TASKLISTS,

        // Extension-specific specs. `footnotes` bundles GFM because
        // remark-gfm (our conformance target) always enables autolink-literal
        // alongside footnotes, so the expected HTML assumes both.
        "footnotes" => FOOTNOTES | GFM,
        "heading_attrs" => HEADING_ATTRIBUTES,
        "math" => MATH,
        // Multi-dollar math only: `$$...$$` and `$$` fences parse, but a lone
        // `$` stays literal (remark-math `singleDollarTextMath: false`).
        "math_multi_dollar" => MATH_MULTI_DOLLAR,
        "strikethrough" => GFM | STRIKETHROUGH,
        "super_sub" => SUPERSCRIPT,
        "table" => TABLES,

        // Regression tests: enable a broad set of extensions so cases that
        // exercise any one of them (GFM, footnotes, tables, heading attrs,
        // …) can coexist in a single spec file. These flags are strictly
        // about what the parser is asked to do here — they are not the
        // default set shipped via the npm/napi binding, which stays
        // close to remark-gfm.
        "regression" => {
            TABLES
                | FOOTNOTES
                | STRIKETHROUGH
                | TASKLISTS
                | HEADING_ATTRIBUTES
                | MATH
                | GFM
                | SUPERSCRIPT
        }

        // Specs that use per-example suffix flags only
        "container_extensions" | "metadata_blocks" | "wikilinks" => 0,

        other => panic!("Unknown spec file: {other}"),
    }
}

#[cfg(feature = "gen-tests")]
pub struct Spec<'a> {
    spec: &'a str,
}

#[cfg(feature = "gen-tests")]
impl<'a> Spec<'a> {
    pub fn new(spec: &'a str) -> Self {
        Spec { spec }
    }
}

#[cfg(feature = "gen-tests")]
pub struct TestCase {
    pub original: String,
    pub expected: String,
    pub smart_punct: bool,
    pub metadata_blocks: bool,
    pub subscript: bool,
    pub wikilinks: bool,
    pub deflists: bool,
    pub container_extensions: bool,
}

#[cfg(feature = "gen-tests")]
impl<'a> Iterator for Spec<'a> {
    type Item = TestCase;

    fn next(&mut self) -> Option<TestCase> {
        let spec = self.spec;
        let prefix = "```````````````````````````````` example";

        let (
            i_start,
            smart_punct,
            metadata_blocks,
            subscript,
            wikilinks,
            deflists,
            container_extensions,
        ) = self.spec.find(prefix).and_then(|pos| {
            let after = pos + prefix.len();
            let tail = &spec[after..];
            let mut flags = [false; 6];
            let (consumed, matched) = if let Some(rest) = tail.strip_prefix("_smartpunct\n") {
                flags[0] = true;
                (tail.len() - rest.len(), true)
            } else if let Some(rest) = tail.strip_prefix("_metadata_blocks\n") {
                flags[1] = true;
                (tail.len() - rest.len(), true)
            } else if let Some(rest) = tail.strip_prefix("_super_sub\n") {
                flags[2] = true;
                (tail.len() - rest.len(), true)
            } else if let Some(rest) = tail.strip_prefix("_wikilinks\n") {
                flags[3] = true;
                (tail.len() - rest.len(), true)
            } else if let Some(rest) = tail.strip_prefix("_deflists\n") {
                flags[4] = true;
                (tail.len() - rest.len(), true)
            } else if let Some(rest) = tail.strip_prefix("_container_extensions\n") {
                flags[5] = true;
                (tail.len() - rest.len(), true)
            } else if tail.starts_with('\n') {
                (1, true)
            } else {
                (0, false)
            };
            if matched {
                Some((
                    after + consumed,
                    flags[0],
                    flags[1],
                    flags[2],
                    flags[3],
                    flags[4],
                    flags[5],
                ))
            } else {
                None
            }
        })?;

        let i_end = self.spec[i_start..]
            .find("\n.\n")
            .map(|pos| (pos + 1) + i_start)?;

        let e_end = self.spec[i_end + 2..]
            .find("````````````````````````````````\n")
            .map(|pos| pos + i_end + 2)?;

        self.spec = &self.spec[e_end + 33..];

        let test_case = TestCase {
            original: spec[i_start..i_end].to_string().replace("→", "\t"),
            expected: spec[i_end + 2..e_end].to_string().replace("→", "\t"),
            smart_punct,
            metadata_blocks,
            subscript,
            wikilinks,
            deflists,
            container_extensions,
        };

        Some(test_case)
    }
}
