// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn container_extensions_test_1() {
    let original = r##":::

content

:::
"##;
    let expected = r##"<p>:::</p>
<p>content</p>
<p>:::</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_2() {
    let original = r##":::
Hi
:::
"##;
    let expected = r##"<p>:::
Hi
:::</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_3() {
    let original = r##":::note
Content here
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_4() {
    let original = r##":::note[Title]
Content
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_5() {
    let original = r##":::warning{.big}
Be careful!
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_6() {
    let original = r##"::::outer
:::inner
Content
:::
::::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_7() {
    let original = r##"::video[Title]{src=video.mp4}
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_8() {
    let original = r##"A :abbr[HTML]{title="HyperText Markup Language"} example.
"##;
    let expected = r##"<p>A  example.</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_9() {
    let original = r##"This :smile is text.
"##;
    let expected = r##"<p>This  is text.</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_10() {
    let original = r##"Hello :smile: world
"##;
    let expected = r##"<p>Hello :smile: world</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_11() {
    let original = r##":::note
Paragraph 1

Paragraph 2
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_12() {
    let original = r##":::note
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_13() {
    let original = r##"**bold after**
:::example
Content
:::
"##;
    let expected = r##"<p><strong>bold after</strong></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_14() {
    let original = r##":::::foo
Hi
:::
::::::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_15() {
    let original = r##"> :::foo
> Hi
"##;
    let expected = r##"<blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_16() {
    let original = r##":::c_d
Hi
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_17() {
    let original = r##":::container
> shouldn't close, right?
> :::
> x
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_18() {
    let original = r##":::a
::::b
:::::c
::::
x
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_19() {
    let original = r##":::a
content :::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_20() {
    // remark-directive closes a whole run of same-length container-
    // directive fences on a single closing `:::`. So the first `:::` here
    // closes both `:::a` and its nested `:::b`; the second `:::` has
    // nothing to close and falls through as literal paragraph text.
    let original = r##":::a
:::b

:::
:::
"##;
    let expected = r##"<p>:::</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_21() {
    let original = r##"::::a
:::b

:::
::::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_22() {
    let original = r##":::a
::::b

::::
:::
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_23() {
    let original = r##"::: note
Hi
:::
"##;
    let expected = r##"<p>::: note
Hi
:::</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_24() {
    let original = r##"::break
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true);
}
