// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn gfm_tasklist_test_1() {
    let original = r##"- [ ] foo
- [x] bar
"##;
    let expected = r##"<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" disabled> foo</li>
<li class="task-list-item"><input type="checkbox" checked disabled> bar</li>
</ul>
"##;

    test_markdown_html(original, expected, 2064, false, false, false, false, false, false);
}

#[test]
fn gfm_tasklist_test_2() {
    let original = r##"- [x] foo
  - [ ] bar
  - [x] baz
- [ ] bim
"##;
    let expected = r##"<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" checked disabled> foo
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" disabled> bar</li>
<li class="task-list-item"><input type="checkbox" checked disabled> baz</li>
</ul>
</li>
<li class="task-list-item"><input type="checkbox" disabled> bim</li>
</ul>
"##;

    test_markdown_html(original, expected, 2064, false, false, false, false, false, false);
}
