// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn math_multi_dollar_test_1() {
    let original = r##"$x=y$
"##;
    let expected = r##"<p>$x=y$</p>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}

#[test]
fn math_multi_dollar_test_2() {
    let original = r##"$50 to $100 billion
"##;
    let expected = r##"<p>$50 to $100 billion</p>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}

#[test]
fn math_multi_dollar_test_3() {
    let original = r##"We spent $5.99 today
"##;
    let expected = r##"<p>We spent $5.99 today</p>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}

#[test]
fn math_multi_dollar_test_4() {
    let original = r##"foo$1+1 = 2$bar
"##;
    let expected = r##"<p>foo$1+1 = 2$bar</p>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}

#[test]
fn math_multi_dollar_test_5() {
    let original = r##"$a$ and $b$
"##;
    let expected = r##"<p>$a$ and $b$</p>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}

#[test]
fn math_multi_dollar_test_6() {
    let original = r##"$$\alpha$$
"##;
    let expected = r##"<p><code class="language-math math-inline">\alpha</code></p>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}

#[test]
fn math_multi_dollar_test_7() {
    let original = r##"$$
\beta+\gamma
$$
"##;
    let expected = r##"<pre><code class="language-math math-display">\beta+\gamma</code></pre>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}

#[test]
fn math_multi_dollar_test_8() {
    let original = r##"We raised $5 to $10 million.

$$
E = mc^2
$$
"##;
    let expected = r##"<p>We raised $5 to $10 million.</p>
<pre><code class="language-math math-display">E = mc^2</code></pre>
"##;

    test_markdown_html(original, expected, 8388608, false, false, false, false, false, false);
}
