// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn math_test_1() {
    let original = r##"$x=y$
"##;
    let expected = r##"<p><code class="language-math math-inline">x=y</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_2() {
    let original = r##"$\sqrt{3x-1}+(1+x)^2$
"##;
    let expected = r##"<p><code class="language-math math-inline">\sqrt{3x-1}+(1+x)^2</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_3() {
    let original = r##"foo$1+1 = 2$bar
"##;
    let expected = r##"<p>foo<code class="language-math math-inline">1+1 = 2</code>bar</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_4() {
    let original = r##"$a$ and $b$
"##;
    let expected = r##"<p><code class="language-math math-inline">a</code> and <code class="language-math math-inline">b</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_5() {
    let original = r##"$a$$b$
"##;
    let expected = r##"<p><code class="language-math math-inline">a$$b</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_6() {
    let original = r##"$5x + 2 =
17$
"##;
    let expected = r##"<p><code class="language-math math-inline">5x + 2 =
17</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_7() {
    let original = r##"$$\alpha$$
"##;
    let expected = r##"<p><code class="language-math math-inline">\alpha</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_8() {
    let original = r##"$a<b>c</b>$
"##;
    let expected = r##"<p><code class="language-math math-inline">a&#x3C;b>c&#x3C;/b></code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_9() {
    let original = r##"$not `code`$
"##;
    let expected = r##"<p><code class="language-math math-inline">not `code`</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_10() {
    let original = r##"$![not an](/image)$
"##;
    let expected = r##"<p><code class="language-math math-inline">![not an](/image)</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_11() {
    let original = r##"$<https://not.a.link/>$
"##;
    let expected = r##"<p><code class="language-math math-inline">&#x3C;https://not.a.link/></code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_12() {
    let original = r##"$&alpha;$
"##;
    let expected = r##"<p><code class="language-math math-inline">&#x26;alpha;</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_13() {
    let original = r##"$ y=x$
"##;
    let expected = r##"<p><code class="language-math math-inline"> y=x</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_14() {
    let original = r##"$y=x $
"##;
    let expected = r##"<p><code class="language-math math-inline">y=x </code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_15() {
    let original = r##"Hello $world.
"##;
    let expected = r##"<p>Hello $world.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_16() {
    let original = r##"Dollar at end of line$
"##;
    let expected = r##"<p>Dollar at end of line$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_17() {
    let original = r##"$\$$
"##;
    let expected = r##"<p>$$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_18() {
    let original = r##"$\{a\,b\}$
"##;
    let expected = r##"<p><code class="language-math math-inline">\{a\,b\}</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_19() {
    let original = r##"_$a$ equals $b$_
"##;
    let expected = r##"<p><em><code class="language-math math-inline">a</code> equals <code class="language-math math-inline">b</code></em></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_20() {
    let original = r##"**$a$ equals $b$**
"##;
    let expected = r##"<p><strong><code class="language-math math-inline">a</code> equals <code class="language-math math-inline">b</code></strong></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_21() {
    let original = r##"a$x$
"##;
    let expected = r##"<p>a<code class="language-math math-inline">x</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_22() {
    let original = r##"$x=y$
"##;
    let expected = r##"<p><code class="language-math math-inline">x=y</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_23() {
    let original = r##"$n$-th order
"##;
    let expected = r##"<p><code class="language-math math-inline">n</code>-th order</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_24() {
    let original = r##"$a <b > c$
"##;
    let expected = r##"<p><code class="language-math math-inline">a &#x3C;b > c</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_25() {
    let original = r##"$[(a+b)c](d+e)$
"##;
    let expected = r##"<p><code class="language-math math-inline">[(a+b)c](d+e)</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_26() {
    let original = r##"${a}_b c_{d}$
"##;
    let expected = r##"<p><code class="language-math math-inline">{a}_b c_{d}</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_27() {
    let original = r##"Thus, $20,000 and USD$30,000 won't parse
"##;
    let expected = r##"<p>Thus, <code class="language-math math-inline">20,000 and USD</code>30,000 won't parse</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_28() {
    let original = r##"It is 2$ for a can of soda, not 1$.
"##;
    let expected = r##"<p>It is 2<code class="language-math math-inline"> for a can of soda, not 1</code>.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_29() {
    let original = r##"I'll give $20 today, if you give me more $ tomorrow.
"##;
    let expected = r##"<p>I'll give <code class="language-math math-inline">20 today, if you give me more </code> tomorrow.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_30() {
    let original = r##"Money adds: $\$X + \$Y = \$Z$.
"##;
    let expected = r##"<p>Money adds: <code class="language-math math-inline">\</code>X + $Y = $Z$.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_31() {
    let original = r##"$not a\
hard break  
either$
"##;
    let expected = r##"<p><code class="language-math math-inline">not a\
hard break  
either</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_32() {
    let original = r##"$\alpha\$
"##;
    let expected = r##"<p><code class="language-math math-inline">\alpha\</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_33() {
    let original = r##"$Inline `first$ then` code
"##;
    let expected = r##"<p><code class="language-math math-inline">Inline `first</code> then` code</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_34() {
    let original = r##"`Code $first` then$ inline
"##;
    let expected = r##"<p><code>Code $first</code> then$ inline</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_35() {
    let original = r##"$$ Display `first $$ then` code
"##;
    let expected = r##"<p><code class="language-math math-inline">Display `first</code> then` code</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_36() {
    let original = r##"`Code $$ first` then $$ display
"##;
    let expected = r##"<p><code>Code $$ first</code> then $$ display</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_37() {
    let original = r##"Oops empty $$ expression.
"##;
    let expected = r##"<p>Oops empty $$ expression.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_38() {
    let original = r##"$x$$$$$$$y$$
"##;
    let expected = r##"<p>$x$$$$$$$y$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_39() {
    let original = r##"$x$$$$$$y$$
"##;
    let expected = r##"<p>$x$$$$$$y$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_40() {
    let original = r##"$$x$$$$$$y$$
"##;
    let expected = r##"<p><code class="language-math math-inline">x$$$$$$y</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_41() {
    let original = r##"alpha$$beta$gamma$$delta
"##;
    let expected = r##"<p>alpha<code class="language-math math-inline">beta$gamma</code>delta</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_42() {
    let original = r##"$x + y - z$

$x + y
- z$

$$ x + y
> z $$
"##;
    let expected = r##"<p><code class="language-math math-inline">x + y - z</code></p>
<p>$x + y</p>
<ul>
<li>z$</li>
</ul>
<pre><code class="language-math math-display">> z $$</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_43() {
    let original = r##"$not

math$

$$
not

math
$$
"##;
    let expected = r##"<p>$not</p>
<p>math$</p>
<pre><code class="language-math math-display">not

math</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_44() {
    let original = r##"- $not
    - *
  math$
"##;
    let expected = r##"<ul>
<li>$not
<ul>
<li>*
math$</li>
</ul>
</li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_45() {
    let original = r##"$$
\beta+\gamma
$$
"##;
    let expected = r##"<pre><code class="language-math math-display">\beta+\gamma</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_46() {
    let original = r##"**Bold**

$$
x = y
$$
"##;
    let expected = r##"<p><strong>Bold</strong></p>
<pre><code class="language-math math-display">x = y</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_47() {
    let original = r##"$$ meta
x
$$
"##;
    let expected = r##"<pre><code class="language-math math-display">x</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_48() {
    let original = r##"$$
$$
"##;
    let expected = r##"<pre><code class="language-math math-display"></code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_49() {
    let original = r##"$$
a
$$

$$
b
$$
"##;
    let expected = r##"<pre><code class="language-math math-display">a</code></pre>
<pre><code class="language-math math-display">b</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_50() {
    let original = r##"$$$
alpha
$$$
"##;
    let expected = r##"<pre><code class="language-math math-display">alpha</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_51() {
    let original = r##"   $$
   x
   $$
"##;
    let expected = r##"<pre><code class="language-math math-display">x</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_52() {
    let original = r##"    $$
    x
    $$
"##;
    let expected = r##"<pre><code>$$
x
$$
</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_53() {
    let original = r##"$$
unterminated
"##;
    let expected = r##"<pre><code class="language-math math-display">unterminated</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_54() {
    let original = r##"- $a$
- $$
  b
  $$
"##;
    let expected = r##"<ul>
<li><code class="language-math math-inline">a</code></li>
<li>
<pre><code class="language-math math-display">b</code></pre>
</li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_55() {
    let original = r##"tango
$$
\alpha
$$
"##;
    let expected = r##"<p>tango</p>
<pre><code class="language-math math-display">\alpha</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_56() {
    let original = r##"$$
\alpha
  $$
"##;
    let expected = r##"<pre><code class="language-math math-display">\alpha</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_57() {
    let original = r##"$$
\alpha
$$  
"##;
    let expected = r##"<pre><code class="language-math math-display">\alpha</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_58() {
    let original = r##"$$

  1
+ 1

= 2

$$
"##;
    let expected = r##"<pre><code class="language-math math-display">
  1
+ 1

= 2
</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_59() {
    let original = r##"Foo \$1$ bar

\$\$
1
\$\$
"##;
    let expected = r##"<p>Foo $1$ bar</p>
<p>$$
1
$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_60() {
    let original = r##"**The Cauchy-Schwarz Inequality**

$$
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
$$
"##;
    let expected = r##"<p><strong>The Cauchy-Schwarz Inequality</strong></p>
<pre><code class="language-math math-display">\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_61() {
    let original = r##"- $a$

  $$
  a
  $$

- $$
  b
  $$
"##;
    let expected = r##"<ul>
<li>
<p><code class="language-math math-inline">a</code></p>
<pre><code class="language-math math-display">a</code></pre>
</li>
<li>
<pre><code class="language-math math-display">b</code></pre>
</li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_62() {
    let original = r##"> $$
> x
> $$
"##;
    let expected = r##"<blockquote>
<pre><code class="language-math math-display">x</code></pre>
</blockquote>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_63() {
    let original = r##"$$
\text{$b$}
$$
"##;
    let expected = r##"<pre><code class="language-math math-display">\text{$b$}</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_64() {
    let original = r##"When $a \ne 0$, there are two solutions to $(ax^2 + bx + c = 0)$ and they are
$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$
"##;
    let expected = r##"<p>When <code class="language-math math-inline">a \ne 0</code>, there are two solutions to <code class="language-math math-inline">(ax^2 + bx + c = 0)</code> and they are
<code class="language-math math-inline">x = {-b \pm \sqrt{b^2-4ac} \over 2a}</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_65() {
    let original = r##"[$a$](x)
"##;
    let expected = r##"<p><a href="x"><code class="language-math math-inline">a</code></a></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_66() {
    let original = r##"$\pi$
'$\pi$
"$\pi$
($\pi$
[$\pi$
{$\pi$
/$\pi$
"##;
    let expected = r##"<p><code class="language-math math-inline">\pi</code>
'<code class="language-math math-inline">\pi</code>
"<code class="language-math math-inline">\pi</code>
(<code class="language-math math-inline">\pi</code>
[<code class="language-math math-inline">\pi</code>
{<code class="language-math math-inline">\pi</code>
/<code class="language-math math-inline">\pi</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_67() {
    let original = r##"_Equation $\Omega(69)$ in italic text_
"##;
    let expected = r##"<p><em>Equation <code class="language-math math-inline">\Omega(69)</code> in italic text</em></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_68() {
    let original = r##"$x$ $`y`$
"##;
    let expected = r##"<p><code class="language-math math-inline">x</code> <code class="language-math math-inline">`y`</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_69() {
    let original = r##"$a <b > c$

$[(a+b)c](d+e)$

${a}_b c_{d}$
"##;
    let expected = r##"<p><code class="language-math math-inline">a &#x3C;b > c</code></p>
<p><code class="language-math math-inline">[(a+b)c](d+e)</code></p>
<p><code class="language-math math-inline">{a}_b c_{d}</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_70() {
    let original = r##"$x = \$$
"##;
    let expected = r##"<p>$x = $$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_71() {
    let original = r##"foo$-1+1 = 2$bar
"##;
    let expected = r##"<p>foo<code class="language-math math-inline">-1+1 = 2</code>bar</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_72() {
    let original = r##"- ![node logo](https://nodejs.org/static/images/logo.svg)
- $x$
"##;
    let expected = r##"<ul>
<li><img src="https://nodejs.org/static/images/logo.svg" alt="node logo"></li>
<li><code class="language-math math-inline">x</code></li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}
