// This file is auto-generated by the build script
// Please, do not modify it manually

pub use super::test_markdown_html;

mod container_extensions;
mod footnotes;
mod gfm_strikethrough;
mod gfm_table;
mod gfm_tasklist;
mod heading_attrs;
mod math;
mod math_multi_dollar;
mod metadata_blocks;
mod regression;
mod smart_punct;
mod spec;
mod strikethrough;
mod super_sub;
mod table;
mod wikilinks;
