// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn super_sub_test_1() {
    let original = r##"^This is super^ ~This is sub~
"##;
    let expected = r##"<p><em>This is super</em> <em>This is sub</em></p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_2() {
    let original = r##"~This is stricken out~
"##;
    let expected = r##"<p><em>This is stricken out</em></p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_3() {
    let original = r##"~This is \~stricken~
"##;
    let expected = r##"<p><em>This is ~stricken</em></p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_4() {
    let original = r##"~This~is~nothing~
"##;
    let expected = r##"<p><em>This</em>is<em>nothing</em></p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_5() {
    let original = r##"~This ~~is not stricken.~
"##;
    let expected = r##"<p><em>This ~~is not stricken.</em></p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_6() {
    let original = r##"~~This ~is~~ stricken.~
"##;
    let expected = r##"<p>~~This ~is~~ stricken.~</p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_7() {
    let original = r##"~This ~~is stricken~ but this is not~~
"##;
    let expected = r##"<p><em>This ~~is stricken</em> but this is not~~</p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_8() {
    let original = r##"H~2~O

y=x^2^a+xb+c
"##;
    let expected = r##"<p>H<em>2</em>O</p>
<p>y=x<em>2</em>a+xb+c</p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_9() {
    let original = r##"~foo~~

^bar^^
"##;
    let expected = r##"<p>~foo~~</p>
<p>^bar^^</p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_10() {
    let original = r##"~foo^~^bar~

*foo_*_bar*
"##;
    let expected = r##"<p><em>foo^</em>^bar~</p>
<p><em>foo_</em>_bar*</p>
"##;

    test_markdown_html(original, expected, 8192, false, false, true, false, false, false);
}
