name: CI

env:
  CARGO_INCREMENTAL: "1"

permissions:
  contents: read

on:
  push:
    branches: [main]
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/*.md"
      - LICENSE
      - "**/*.gitignore"
      - .editorconfig
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy, rustfmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Codegen up to date
        run: pnpm codegen:check

      - name: Lint JS
        run: pnpm oxlint

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rust tests
        run: cargo test

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build TypeScript
        run: pnpm run build:ts
        working-directory: packages/satteri

      - name: Build NAPI binding
        run: pnpm run build:binary:native:debug
        working-directory: packages/satteri

      - name: Test
        run: pnpm test
        working-directory: packages/satteri
